### PR TITLE
Add sanity checks on PRs

### PR DESCRIPTION
**Pull request by tonyskapunk**
Include sanity checks for the modules and general validation for playbooks included in the repo.
Also cleans up demo play and module.

Fix: #7

### CODE REVIEW

**Review by vjayaramrh — DISMISSED** [review]
Looks good to me

**Comment by tonyskapunk** [comment]
@vjayaramrh the failure is due to lack of license, do you have any in mind?

**Comment by tonyskapunk** [comment]
@vjayaramrh PTAL

**Review by vjayaramrh — APPROVED** [review]

**Review by clwheel — APPROVED** [review]
LGTM

**Pull request merged**
